Repository perkeep/perkeep, pull requests merged in 2019-06, with the labels that each got.

#1259 test/dockertest: allow the <repository:tag> syntax for images
  pkg/test/dockertest/docker.go
Labels: Testing, docker

#1260 server/perkeepd/ui: Implement blob audio
  server/perkeepd/ui/audio_detail.css
  server/perkeepd/ui/audio_detail.js
  server/perkeepd/ui/blob_item_audio.css
  server/perkeepd/ui/blob_item_audio_content.js
  server/perkeepd/ui/index.css
  server/perkeepd/ui/index.html
  server/perkeepd/ui/index.js
Labels: WebUI

#1267 docs/server-config: mention diskpacked perf trade-off.
  doc/server-config.md
Labels: cla: yes
