Repository perkeep/perkeep, pull requests merged in 2021-07, with the labels that each got.

#1379 make codebase go-vet-clean
  .github/workflows/tests-lint.yaml
  cmd/pk-get/get.go
  cmd/pk-put/discard.go
  cmd/pk-put/kvcache.go
  cmd/pk/list.go
  internal/netutil/ident.go
  pkg/blobserver/b2/b2.go
  pkg/blobserver/blobhub_test.go
  pkg/blobserver/blobpacked/blobpacked_test.go
  pkg/blobserver/blobpacked/stream_test.go
  pkg/blobserver/encrypt/encrypt_test.go
  pkg/blobserver/files/enumerate_test.go
  pkg/blobserver/google/drive/enumerate.go
  pkg/blobserver/handlers/upload.go
  pkg/blobserver/localdisk/localdisk_test.go
  pkg/blobserver/memory/mem.go
  pkg/blobserver/memory/mem_test.go
  pkg/blobserver/mergedenum_test.go
  pkg/blobserver/multistream_test.go
  pkg/blobserver/namespace/ns.go
  pkg/blobserver/proxycache/proxycache_test.go
  pkg/blobserver/shard/shard_test.go
  pkg/blobserver/stats/statreceiver.go
  pkg/blobserver/stats/statreceiver_test.go
  pkg/blobserver/storagetest/storagetest.go
  pkg/blobserver/sync_test.go
  pkg/client/android/androidx.go
  pkg/client/client.go
  pkg/client/config.go
  pkg/client/upload.go
  pkg/fs/rover.go
  pkg/gc/gc.go
  pkg/gpgchallenge/gpg.go
  pkg/importer/flickr/flickr.go
  pkg/importer/importer.go
  pkg/importer/pinboard/pinboard_test.go
  pkg/importer/plaid/plaid.go
  pkg/importer/twitter/twitter.go
  pkg/importer/twitter/twitter_test.go
  pkg/index/index_test.go
  pkg/index/receive.go
  pkg/jsonsign/jsonsign_test.go
  pkg/schema/fileread_test.go
  pkg/schema/schema_test.go
  pkg/search/describe.go
  pkg/search/handler_test.go
  pkg/search/websocket.go
  pkg/server/app/app.go
  pkg/server/wizard.go
  pkg/test/blob.go
  website/pk-web/pkweb.go
Labels: cla: no, needs review

#1295 internal/httputil: do not throw away server responses beyond 8MB
  internal/httputil/httputil.go
Labels: cla: yes

#1397 go 1.15 -> 1.16
  .github/workflows/tests-lint.yaml
  .github/workflows/tests-linux.yml
  .github/workflows/tests-macos.yml
  .github/workflows/tests-tidy.yaml
  .github/workflows/tests-windows.yml
  go.mod
  go.sum
  make.go
  pkg/blobserver/encrypt/encrypt_test.go
  pkg/search/describe_test.go
Labels: cla: yes

#1383 doc: document all environement variables
  .github/workflows/tests-lint.yaml
  dev/envvardoc/envvardoc.go
  doc/README.md
  doc/environment-vars.md
Labels: cla: yes, needs review

#1396 move to go:embed
  .gitignore
  app/publisher/fileembed.go
  app/publisher/main.go
  app/scanningcabinet/handler.go
  app/scanningcabinet/ui/fileembed.go
  clients/web/embed/fontawesome/fileembed.go
  clients/web/embed/glitch/fileembed.go
  clients/web/embed/keepy/fileembed.go
  clients/web/embed/leaflet/fileembed.go
  clients/web/embed/less/fileembed.go
  clients/web/embed/opensans/fileembed.go
  clients/web/embed/react/fileembed.go
  internal/closure/gendeps.go
  make.go
  pkg/fileembed/fileembed.go
  pkg/fileembed/genfileembed/genfileembed.go
  pkg/server/fileembed.go
  pkg/server/root.go
  pkg/server/ui.go
  server/perkeepd/ui/fileembed.go
  server/perkeepd/ui/fileembed_normal.go
Labels: cla: yes

#1394 Update deps
  .github/workflows/tests-linux.yml
  .github/workflows/tests-macos.yml
  go.mod
  go.sum
  pkg/blobserver/sftp/sftp.go
  pkg/blobserver/sftp/sftp_test.go
  pkg/search/handler_test.go
Labels: cla: yes
